development:
  adapter: async
  # adapter: any_cable
  # adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: evercell-backend_production

test:
  adapter: async
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: evercell-backend_production

production:
  adapter: redis
  url: <%= ENV.fetch("REDISTOGO_URL") { "redis://localhost:6379/1" } %>
  :host: dory.redistogo.com
  :port: 11599
  :password: ENV['SECRET_PASS']
  :inline: true
  :timeout: 1
  channel_prefix: evercell-backend_production
  # url: <%= ENV.fetch("REDIS_URL") { "redis://10.113.106.139:6379/1" } %>
  # channel_prefix: evercell-backend_production

# production: *redis
# development: *redis
# test: *redis

